name: Deploy
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git Version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Install dependencies
        run: npm install
      - name: Build Anutils
        run: npx ng build anutils --prod
      - name: Publishing Anutils
        run: |
          cd dist/anutils
          npm version $RELEASE_VERSION
          npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
          npm whoami
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
