name: Deploy Library

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: npm install
      - name: Build Anutils
        run: npx ng build anutils --prod
      - name: Publishing Anutils
        working-directory: dist/anutils
        run: |
          npm version $RELEASE_VERSION
          npm publish --access public --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
