name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git Version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

        # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Build Anutils
        run: npx ng build anutils --prod

      - name: Publishing Anutils
        run: |
          cd dist/anutils
          npm config set //registry.npmjs.org/:_authToken=$NPTOKEN
          npm publish --access public --verbose
          npm whoami
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPTOKEN: ${{ secrets.NPM_TOKEN }}
